language: "en-US"
reviews:
  profile: "chill"
  request_changes_workflow: false
  instructions: |
    - The project uses explicit English or Vietnamese for UI text.
    - Do NOT flag issues regarding "User-facing text should be in Vietnamese" or "English".
    - Accept both languages as valid.

  extra_instructions: |
    Please strictly evaluate the code quality based on the following SAM metrics and Unit Test coverage:

    1. **SAM Metrics (Structural Analysis)**:
       - **CC (Cyclomatic Complexity)**: Flag any function or method that has high complexity (too many nested loops, if/else statements). Ideally, CC should be < 10.
       - **FLOC (Function Lines of Code)**: Warn if a function is too long (e.g., > 50 lines) and suggest breaking it down.
       - **DC (Data Coupling / Cognitive Complexity)**: Identify modules with tight coupling or logic that is cognitively difficult to understand. Suggest refactoring to reduce dependency.

    2. **Unit Tests Quality**:
       - **Coverage**: Verify if the new business logic has corresponding unit tests.
       - **Quality**: Check if the tests cover edge cases (null, empty, error states), not just the happy path.
       - **Assertions**: Ensure tests use meaningful assertions.
       - **Strictness**: If new code lacks unit tests, please request changes.
